spring:
  application.name: Lab03 AWS BedrockAI
  main.web-application-type: none     # Do not start a web server.
  
  ai:
    retry:
      max-attempts: 1    # Maximum number of retry attempts.
    bedrock:
      aws.region: us-west-2
      titan:
        chat:
          enabled: true